### ISSUE TITLE
Autocomplete area not showing up when pasting text from clipboard

### ISSUE THREAD

**Issue by isra00** [kraaden/autocomplete#78]
![output](https://user-images.githubusercontent.com/94328/130297411-919f5169-42e4-4724-9ec3-c20676dc8e15.gif)

As you can see, the autocomplete area shows up only after changing the text through the keyboard (in this case adding and then removing a space).

This happens on Chrome/Android, but not on Firefox/Android, where it shows up properly.
On desktop (Windows) it works in both browsers (last versions).
Thank you!

**Comment by tomickigrzegorz** [comment]
It works on firefox/android I tested.

**Comment by ofrias** [comment]
Once the [special Firefox Mobile code](https://github.com/kraaden/autocomplete/issues/99) is removed, both Chrome and Firefox on Android will exhibit this issue.
You can reproduce the issue on desktop too, as long as you paste the text using the mouse right button (instead of CTRL+V, which fires the `keyup` event).
It seems that the input `change` event should be handled too, in addition to `keyup`.

**Comment by denis-taran** [comment]
This issue should be fixed in the last version:

    npm install autocompleter@8.0.0-alpha.1
